/**
 * Direct protocol test: call the bundled Worker's fetch() handler IN-PROCESS
 * with crafted smart-http requests — no HTTP server, no network, no flaky
 * background process. Verifies the full push + fetch (upload-pack + receive-pack)
 * round trip against a memory backend, plus that objects/refs end up stored.
 *
 * Uses a REAL pack generated by `git` (via the repo fixture), so it exercises
 * parsePack + writeObject + CAS ref update exactly as a real client would.
 *
 * Run: node --experimental-strip-types test/protocol.ts
 */

import { spawnSync, spawn } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync, mkdirSync, readFileSync, readdirSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const worker: any = await import(new URL("./.bundle-worker.mjs", import.meta.url).href);
const handler = worker.default;
const env = { STORAGE_TYPE: "memory", STORAGE_PREFIX: "", AUTH_TOKEN: "" };

async function call(method: string, path: string, opts: { body?: Uint8Array; headers?: Record<string, string> } = {}): Promise<{ status: number; body: Uint8Array; headers: Headers }> {
  const url = `http://test${path}`;
  const req = new Request(url, {
    method,
    headers: opts.headers ?? {},
    body: method === "GET" || method === "HEAD" ? undefined : (opts.body as any),
  });
  const resp: Response = await handler.fetch(req, env);
  return { status: resp.status, body: new Uint8Array(await resp.arrayBuffer()), headers: resp.headers };
}

function sh(args: string[], cwd: string) {
  const r = spawnSync(args[0], args.slice(1), { cwd, encoding: "utf8" });
  if (r.status !== 0) throw new Error(`${args.join(" ")} failed: ${r.stderr}`);
  return r.stdout.trim();
}

// --- Build a real repo with many objects + deltas to push ---
const root = mkdtempSync(join(tmpdir(), "proto-"));
const repo = join(root, "repo");
mkdirSync(repo, { recursive: true });
sh(["git", "init", "-q", "-b", "main"], repo);
sh(["git", "config", "user.email", "t@t.t"], repo);
sh(["git", "config", "user.name", "P"], repo);
mkdirSync(join(repo, "src"), { recursive: true });
// Several commits that modify the same file → git emits OFS_DELTA objects,
// exercising the pack index + delta-resolution read path.
writeFileSync(join(repo, "README.md"), "# Proto\n\nMulti-object test.\n");
let body = "";
for (let i = 0; i < 40; i++) body += `line ${i}: some content\n`;
writeFileSync(join(repo, "src", "a.ts"), body);
for (let c = 0; c < 8; c++) {
  writeFileSync(join(repo, "src", `f${c}.ts`), `// file ${c}\nexport const x = ${c};\n`);
  body = body + `\n// appended in commit ${c}\n`;
  writeFileSync(join(repo, "src", "a.ts"), body);
  sh(["git", "add", "."], repo);
  sh(["git", "commit", "-q", `-m commit ${c}`], repo);
}

// Build a pack of all objects (this is what receive-pack receives).
const packBase = join(root, "p");
await new Promise<void>((res, rej) => {
  const a = spawn("git", ["rev-list", "--objects", "--all"], { cwd: repo });
  const b = spawn("git", ["pack-objects", packBase], { cwd: repo });
  a.stdout.pipe(b.stdin);
  b.on("exit", (c) => (c === 0 ? res() : rej(new Error("pack exit " + c))));
});
const packFile = readdirSync(root).find((f) => /^p-[0-9a-f]+\.pack$/.test(f))!;
const pack = readFileSync(join(root, packFile));

const headSha = sh(["git", "rev-parse", "HEAD"], repo);
console.log("fixture: head", headSha.slice(0, 8), "pack", pack.length, "bytes");

// === STEP 1: receive-pack info/refs (empty repo) ===
console.log("\n[1] receive-pack info/refs...");
const r1 = await call("GET", "/myrepo/info/refs?service=git-receive-pack");
if (r1.status !== 200) throw new Error("info/refs status " + r1.status);
const r1text = new TextDecoder().decode(r1.body);
if (!r1text.includes("# service=git-receive-pack")) throw new Error("no service banner");
if (!r1text.includes("capabilities^{}")) throw new Error("no empty-repo advertisement");
console.log("    ok (service banner + empty-repo caps)");

// === STEP 2: receive-pack POST (the push) ===
// Build the pkt-line command section: "<old> <new> <ref>\0caps\n" then flush, then pack.
const oldSha = "0".repeat(40);
const caps = "report-status side-band-64k ofs-delta";
const cmdLine = `${oldSha} ${headSha} refs/heads/main\0${caps}\n`;
const cmdPkt = pkt(cmdLine);
const flush = new Uint8Array([0x30, 0x30, 0x30, 0x30]); // "0000"
const postBody = concat(cmdPkt, flush, pack);

console.log("\n[2] receive-pack POST (push the pack)...");
const r2 = await call("POST", "/myrepo/git-receive-pack", { body: postBody });
if (r2.status !== 200) throw new Error("receive-pack status " + r2.status);
const r2text = new TextDecoder().decode(stripSideband(r2.body));
if (!r2text.includes("unpack ok")) throw new Error("no 'unpack ok': " + JSON.stringify(r2text.slice(0, 100)));
if (!r2text.includes("ok refs/heads/main")) throw new Error("no 'ok refs/heads/main': " + JSON.stringify(r2text.slice(0, 100)));
console.log("    unpack ok + ok refs/heads/main");

// === STEP 3: verify ref + objects actually got written ===
console.log("\n[3] verify state via upload-pack info/refs...");
const r3 = await call("GET", "/myrepo/info/refs?service=git-upload-pack", { headers: { "Git-Protocol": "version=2" } });
const r3text = new TextDecoder().decode(r3.body);
if (!r3text.includes("version 2")) throw new Error("upload-pack not v2");
console.log("    upload-pack advertises v2");

// v2 ls-refs
const lsBody = concat(pkt("command=ls-refs\n"), pkt("peel\n"), pkt("symrefs\n"), toBytes(flushStr()));
const r4 = await call("POST", "/myrepo/git-upload-pack", { body: lsBody, headers: { "Git-Protocol": "version=2" } });
const r4text = new TextDecoder().decode(dePkt(r4.body));
if (!r4text.includes(`${headSha} refs/heads/main`)) throw new Error("ls-refs missing main: " + JSON.stringify(r4text.slice(0, 100)));
console.log("    ls-refs returns refs/heads/main @ " + headSha.slice(0, 8));

// === STEP 4: v2 fetch → pack, then git verifies it ===
console.log("\n[4] v2 fetch → pack...");
const fetchBody = concat(pkt("command=fetch\n"), pkt(`want ${headSha}\n`), toBytes(flushStr()), pkt("done\n"), toBytes(flushStr()));
const r5 = await call("POST", "/myrepo/git-upload-pack", { body: fetchBody, headers: { "Git-Protocol": "version=2" } });
const fetchedPack = stripSideband(r5.body);
if (fetchedPack.length < 12 || new TextDecoder().decode(fetchedPack.subarray(0, 4)) !== "PACK") {
  // could be prefixed with "packfile\n" pkt then sideband; extract the PACK
  throw new Error("fetch did not return a pack: " + JSON.stringify(new TextDecoder().decode(fetchedPack.subarray(0, 30))));
}
writeFileSync(join(root, "fetched.pack"), fetchedPack);
// git index-pack + verify
const ip = spawnSync("git", ["index-pack", join(root, "fetched.pack")], { cwd: root, encoding: "utf8" });
if (ip.status !== 0) throw new Error("git index-pack rejected fetched pack: " + ip.stderr);
// unpack into a fresh repo and check content
const repo2 = join(root, "repo2");
mkdirSync(repo2, { recursive: true });
sh(["git", "init", "-q", "-b", "main"], repo2);
const uo = spawnSync("git", ["unpack-objects", "-q"], { cwd: repo2, input: readFileSync(join(root, "fetched.pack")), encoding: null });
if (uo.status !== 0) throw new Error("unpack-objects failed");
// point HEAD/main at the fetched commit and read tree
sh(["git", "update-ref", "refs/heads/main", headSha], repo2);
sh(["git", "symbolic-ref", "HEAD", "refs/heads/main"], repo2);
const show = spawnSync("git", ["show", "HEAD:README.md"], { cwd: repo2, encoding: "utf8" });
if (!show.stdout.includes("Multi-object test")) throw new Error("fetched content mismatch: " + show.stdout.slice(0, 80));
const show2 = spawnSync("git", ["show", "HEAD:src/a.ts"], { cwd: repo2, encoding: "utf8" });
if (!show2.stdout.includes("line 0:") || !show2.stdout.includes("appended in commit 7")) {
  throw new Error("fetched nested file mismatch (delta not resolved correctly): " + show2.stdout.slice(0, 120));
}
console.log("    fetched pack unpacks to correct tree (README + src/a.ts with deltas)");

if (!process.env.KEEP) rmSync(root, { recursive: true, force: true });
console.log("\nALL PROTOCOL TESTS PASSED ✅");
console.log("  receive-pack: info/refs + POST(push) → unpack ok + ref CAS");
console.log("  upload-pack v2: info/refs + ls-refs + fetch → pack git accepts");

// helpers
function pkt(s: string): Uint8Array {
  const data = new TextEncoder().encode(s);
  const len = (data.length + 4).toString(16).padStart(4, "0");
  const out = new Uint8Array(data.length + 4);
  out.set(new TextEncoder().encode(len), 0);
  out.set(data, 4);
  return out;
}
function flushStr(): string { return "0000"; }
function toBytes(s: string): Uint8Array { return new TextEncoder().encode(s); }
function concat(...parts: Uint8Array[]): Uint8Array {
  let total = 0; for (const p of parts) total += p.length;
  const out = new Uint8Array(total); let o = 0;
  for (const p of parts) { out.set(p, o); o += p.length; }
  return out;
}
// Strip pkt-line framing: concatenate all payload bytes (skip flush/length headers).
function dePkt(body: Uint8Array): Uint8Array {
  const out: Uint8Array[] = [];
  let off = 0;
  while (off + 4 <= body.length) {
    const lenHex = new TextDecoder().decode(body.subarray(off, off + 4));
    const len = parseInt(lenHex, 16);
    if (Number.isNaN(len)) break;
    off += 4;
    if (len === 0) continue; // flush
    out.push(body.subarray(off, off + len - 4));
    off += len - 4;
  }
  return concat(...out);
}
// If the body is side-band-64k framed (pkt-lines with a 1-byte channel prefix),
// extract only channel-1 data. Otherwise return as-is (de-pkt-lined).
function stripSideband(body: Uint8Array): Uint8Array {
  // Heuristic: if body starts with a 4-hex pkt length, treat as pkt-framed.
  const head = new TextDecoder().decode(body.subarray(0, 4));
  if (!/^[0-9a-f]{4}$/.test(head)) return body;
  const out: Uint8Array[] = [];
  let off = 0;
  while (off + 4 <= body.length) {
    const lenHex = new TextDecoder().decode(body.subarray(off, off + 4));
    const len = parseInt(lenHex, 16);
    if (Number.isNaN(len)) break;
    off += 4;
    if (len === 0) continue; // flush
    const payload = body.subarray(off, off + len - 4);
    off += len - 4;
    if (payload.length >= 1) {
      const channel = payload[0];
      if (channel === 1) out.push(payload.subarray(1)); // data
      // channel 2 = progress, 3 = error — ignore for data extraction
    }
  }
  return concat(...out);
}
